# Generated by Django 4.0.5 on 2022-07-25 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_myuser_model_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser_model',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
