# Generated by Django 4.0.5 on 2022-07-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_myuser_model_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser_model',
            name='status',
            field=models.CharField(choices=[('approve', 'approve'), ('reject', 'reject')], max_length=30),
        ),
    ]
